// Romanian counties (județe) with their main cities/towns.
// Used to constrain checkout address input so carriers (eAWB) receive valid locality+county pairs.
export const ROMANIA_LOCATIONS: Record<string, string[]> = {
  "Alba": ["Alba Iulia", "Aiud", "Blaj", "Sebeș", "Cugir", "Ocna Mureș", "Câmpeni", "Zlatna", "Abrud", "Baia de Arieș", "Teiuș"],
  "Arad": ["Arad", "Ineu", "Lipova", "Pâncota", "Sebiș", "Nădlac", "Chișineu-Criș", "Curtici", "Sântana", "Pecica"],
  "Argeș": ["Pitești", "Câmpulung", "Curtea de Argeș", "Mioveni", "Ștefănești", "Costești", "Topoloveni"],
  "Bacău": ["Bacău", "Onești", "Moinești", "Comănești", "Buhuși", "Târgu Ocna", "Slănic-Moldova", "Dărmănești"],
  "Bihor": ["Oradea", "Salonta", "Marghita", "Beiuș", "Aleșd", "Ștei", "Valea lui Mihai", "Nucet", "Vașcău"],
  "Bistrița-Năsăud": ["Bistrița", "Beclean", "Năsăud", "Sângeorz-Băi"],
  "Botoșani": ["Botoșani", "Dorohoi", "Darabani", "Săveni", "Ștefănești", "Flămânzi", "Bucecea"],
  "Brașov": ["Brașov", "Făgăraș", "Săcele", "Codlea", "Zărnești", "Râșnov", "Victoria", "Rupea", "Predeal", "Ghimbav"],
  "Brăila": ["Brăila", "Ianca", "Însurăței", "Făurei"],
  "București": ["București", "Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6"],
  "Buzău": ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pogoanele", "Pătârlagele"],
  "Caraș-Severin": ["Reșița", "Caransebeș", "Bocșa", "Oravița", "Moldova Nouă", "Oțelu Roșu", "Băile Herculane", "Anina"],
  "Călărași": ["Călărași", "Oltenița", "Budești", "Lehliu-Gară", "Fundulea"],
  "Cluj": ["Cluj-Napoca", "Turda", "Dej", "Câmpia Turzii", "Gherla", "Huedin"],
  "Constanța": ["Constanța", "Mangalia", "Medgidia", "Năvodari", "Cernavodă", "Ovidiu", "Eforie", "Techirghiol", "Hârșova", "Murfatlar", "Băneasa", "Negru Vodă"],
  "Covasna": ["Sfântu Gheorghe", "Târgu Secuiesc", "Covasna", "Baraolt", "Întorsura Buzăului"],
  "Dâmbovița": ["Târgoviște", "Moreni", "Pucioasa", "Găești", "Titu", "Fieni", "Răcari"],
  "Dolj": ["Craiova", "Băilești", "Calafat", "Filiași", "Segarcea", "Dăbuleni", "Bechet"],
  "Galați": ["Galați", "Tecuci", "Târgu Bujor", "Berești"],
  "Giurgiu": ["Giurgiu", "Bolintin-Vale", "Mihăilești"],
  "Gorj": ["Târgu Jiu", "Motru", "Rovinari", "Bumbești-Jiu", "Târgu Cărbunești", "Novaci", "Turceni", "Țicleni", "Tismana"],
  "Harghita": ["Miercurea Ciuc", "Odorheiu Secuiesc", "Gheorgheni", "Toplița", "Cristuru Secuiesc", "Bălan", "Borsec", "Băile Tușnad", "Vlăhița"],
  "Hunedoara": ["Deva", "Hunedoara", "Petroșani", "Lupeni", "Vulcan", "Orăștie", "Brad", "Petrila", "Simeria", "Călan", "Hațeg", "Uricani", "Aninoasa", "Geoagiu"],
  "Ialomița": ["Slobozia", "Fetești", "Urziceni", "Țăndărei", "Amara", "Căzănești", "Fierbinți-Târg"],
  "Iași": ["Iași", "Pașcani", "Hârlău", "Târgu Frumos", "Podu Iloaiei"],
  "Ilfov": ["Buftea", "Voluntari", "Pantelimon", "Popești-Leordeni", "Bragadiru", "Otopeni", "Chitila", "Măgurele", "Mogoșoaia"],
  "Maramureș": ["Baia Mare", "Sighetu Marmației", "Borșa", "Vișeu de Sus", "Târgu Lăpuș", "Baia Sprie", "Cavnic", "Seini", "Ulmeni", "Săliștea de Sus", "Șomcuta Mare", "Dragomirești"],
  "Mehedinți": ["Drobeta-Turnu Severin", "Orșova", "Strehaia", "Vânju Mare", "Baia de Aramă"],
  "Mureș": ["Târgu Mureș", "Reghin", "Sighișoara", "Târnăveni", "Luduș", "Sovata", "Iernut", "Sângeorgiu de Pădure", "Miercurea Nirajului", "Sărmașu", "Ungheni"],
  "Neamț": ["Piatra Neamț", "Roman", "Târgu Neamț", "Bicaz", "Roznov"],
  "Olt": ["Slatina", "Caracal", "Balș", "Corabia", "Drăgănești-Olt", "Scornicești", "Piatra-Olt", "Potcoava"],
  "Prahova": ["Ploiești", "Câmpina", "Băicoi", "Mizil", "Vălenii de Munte", "Sinaia", "Bușteni", "Comarnic", "Breaza", "Slănic", "Azuga", "Boldești-Scăeni", "Plopeni", "Urlați"],
  "Satu Mare": ["Satu Mare", "Carei", "Negrești-Oaș", "Tășnad", "Ardud", "Livada"],
  "Sălaj": ["Zalău", "Șimleu Silvaniei", "Jibou", "Cehu Silvaniei"],
  "Sibiu": ["Sibiu", "Mediaș", "Cisnădie", "Agnita", "Avrig", "Copșa Mică", "Dumbrăveni", "Săliște", "Ocna Sibiului", "Tălmaciu", "Miercurea Sibiului"],
  "Suceava": ["Suceava", "Fălticeni", "Rădăuți", "Câmpulung Moldovenesc", "Vatra Dornei", "Gura Humorului", "Siret", "Solca", "Broșteni", "Dolhasca", "Salcea", "Vicovu de Sus", "Milișăuți", "Frasin", "Cajvana", "Liteni"],
  "Teleorman": ["Alexandria", "Roșiorii de Vede", "Turnu Măgurele", "Zimnicea", "Videle"],
  "Timiș": ["Timișoara", "Lugoj", "Sânnicolau Mare", "Jimbolia", "Buziaș", "Deta", "Făget", "Ciacova", "Gătaia", "Recaș"],
  "Tulcea": ["Tulcea", "Măcin", "Babadag", "Isaccea", "Sulina"],
  "Vaslui": ["Vaslui", "Bârlad", "Huși", "Negrești", "Murgeni"],
  "Vâlcea": ["Râmnicu Vâlcea", "Drăgășani", "Băbeni", "Băile Govora", "Băile Olănești", "Bălcești", "Berbești", "Brezoi", "Călimănești", "Horezu", "Ocnele Mari"],
  "Vrancea": ["Focșani", "Adjud", "Mărășești", "Odobești", "Panciu"],
};

export const ROMANIA_COUNTIES = Object.keys(ROMANIA_LOCATIONS).sort();