import type { LayoutGrammarId, TypographyRoleStyle, TypographySystem, TypographyRoleId } from './types';

function role(
  partial: TypographyRoleStyle
): TypographyRoleStyle {
  return partial;
}

const quietKicker: TypographyRoleStyle = role({
  family: 'body',
  minPx: 12,
  maxPx: 13,
  vw: 0.7,
  lineHeight: 1.2,
  letterSpacing: '0.28em',
  weight: 500,
  transform: 'uppercase',
  maxCh: 42,
  align: 'start',
  wrapping: 'normal',
});

function actionRole(align: TypographyRoleStyle['align'] = 'start'): TypographyRoleStyle {
  return role({
    family: 'body',
    minPx: 13,
    maxPx: 15,
    vw: 0.85,
    lineHeight: 1.2,
    letterSpacing: '0.08em',
    weight: 600,
    transform: 'uppercase',
    maxCh: 28,
    align,
    wrapping: 'normal',
  });
}

export const GRAMMAR_TYPOGRAPHY: Record<LayoutGrammarId, TypographySystem> = {
  editorial_asymmetric: {
    grammarId: 'editorial_asymmetric',
    displayFont: 'Cormorant Garamond',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Manrope',
    scaleRatio: 1.333,
    measureCh: 42,
    mobileScale: 0.86,
    roles: {
      display: role({
        family: 'display',
        minPx: 42,
        maxPx: 92,
        vw: 6.4,
        lineHeight: 0.94,
        letterSpacing: '-0.035em',
        weight: 500,
        transform: 'none',
        maxCh: 14,
        align: 'start',
        wrapping: 'balance',
      }),
      editorialHeading: role({
        family: 'display',
        minPx: 28,
        maxPx: 48,
        vw: 3.2,
        lineHeight: 1.05,
        letterSpacing: '-0.03em',
        weight: 500,
        transform: 'none',
        maxCh: 18,
        align: 'end',
        wrapping: 'balance',
      }),
      sectionHeading: role({
        family: 'display',
        minPx: 22,
        maxPx: 32,
        vw: 2.1,
        lineHeight: 1.15,
        letterSpacing: '-0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 22,
        align: 'start',
        wrapping: 'pretty',
      }),
      body: role({
        family: 'body',
        minPx: 16,
        maxPx: 18,
        vw: 1.05,
        lineHeight: 1.65,
        letterSpacing: '0',
        weight: 400,
        transform: 'none',
        maxCh: 42,
        align: 'start',
        wrapping: 'pretty',
      }),
      supporting: role({
        family: 'body',
        minPx: 14,
        maxPx: 15,
        vw: 0.9,
        lineHeight: 1.55,
        letterSpacing: '0.01em',
        weight: 400,
        transform: 'none',
        maxCh: 36,
        align: 'start',
        wrapping: 'pretty',
      }),
      kicker: quietKicker,
      navigation: role({
        family: 'body',
        minPx: 14,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.2,
        letterSpacing: '0.08em',
        weight: 500,
        transform: 'none',
        maxCh: 20,
        align: 'end',
        wrapping: 'normal',
      }),
      price: role({
        family: 'body',
        minPx: 16,
        maxPx: 20,
        vw: 1.1,
        lineHeight: 1.2,
        letterSpacing: '0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 12,
        align: 'start',
        wrapping: 'normal',
      }),
      action: actionRole('start'),
    },
  },

  cinematic_full_bleed: {
    grammarId: 'cinematic_full_bleed',
    displayFont: 'Outfit',
    headingFont: 'Outfit',
    bodyFont: 'DM Sans',
    scaleRatio: 1.25,
    measureCh: 34,
    mobileScale: 0.84,
    roles: {
      display: role({
        family: 'display',
        minPx: 44,
        maxPx: 86,
        vw: 6.2,
        lineHeight: 0.98,
        letterSpacing: '-0.04em',
        weight: 500,
        transform: 'none',
        maxCh: 16,
        align: 'start',
        wrapping: 'balance',
      }),
      editorialHeading: role({
        family: 'display',
        minPx: 26,
        maxPx: 40,
        vw: 2.8,
        lineHeight: 1.08,
        letterSpacing: '-0.03em',
        weight: 500,
        transform: 'none',
        maxCh: 20,
        align: 'start',
        wrapping: 'balance',
      }),
      sectionHeading: role({
        family: 'heading',
        minPx: 18,
        maxPx: 26,
        vw: 1.6,
        lineHeight: 1.2,
        letterSpacing: '-0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 24,
        align: 'start',
        wrapping: 'pretty',
      }),
      body: role({
        family: 'body',
        minPx: 15,
        maxPx: 17,
        vw: 1,
        lineHeight: 1.55,
        letterSpacing: '0.01em',
        weight: 400,
        transform: 'none',
        maxCh: 34,
        align: 'start',
        wrapping: 'pretty',
      }),
      supporting: role({
        family: 'body',
        minPx: 13,
        maxPx: 14,
        vw: 0.85,
        lineHeight: 1.5,
        letterSpacing: '0.02em',
        weight: 400,
        transform: 'none',
        maxCh: 32,
        align: 'start',
        wrapping: 'pretty',
      }),
      kicker: role({
        family: 'body',
        minPx: 10,
        maxPx: 11,
        vw: 0.65,
        lineHeight: 1.2,
        letterSpacing: '0.34em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 28,
        align: 'start',
        wrapping: 'normal',
      }),
      navigation: role({
        family: 'body',
        minPx: 14,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.2,
        letterSpacing: '0.06em',
        weight: 500,
        transform: 'none',
        maxCh: 16,
        align: 'end',
        wrapping: 'normal',
      }),
      price: role({
        family: 'body',
        minPx: 16,
        maxPx: 20,
        vw: 1.1,
        lineHeight: 1.2,
        letterSpacing: '0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 12,
        align: 'start',
        wrapping: 'normal',
      }),
      action: actionRole('start'),
    },
  },

  product_monument: {
    grammarId: 'product_monument',
    displayFont: 'Fraunces',
    headingFont: 'Fraunces',
    bodyFont: 'DM Sans',
    scaleRatio: 1.2,
    measureCh: 36,
    mobileScale: 0.88,
    roles: {
      display: role({
        family: 'display',
        minPx: 38,
        maxPx: 68,
        vw: 4.6,
        lineHeight: 1.02,
        letterSpacing: '-0.03em',
        weight: 500,
        transform: 'none',
        maxCh: 12,
        align: 'start',
        wrapping: 'balance',
      }),
      editorialHeading: role({
        family: 'display',
        minPx: 22,
        maxPx: 34,
        vw: 2.2,
        lineHeight: 1.12,
        letterSpacing: '-0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 16,
        align: 'start',
        wrapping: 'balance',
      }),
      sectionHeading: role({
        family: 'heading',
        minPx: 16,
        maxPx: 22,
        vw: 1.3,
        lineHeight: 1.25,
        letterSpacing: '-0.015em',
        weight: 500,
        transform: 'none',
        maxCh: 20,
        align: 'start',
        wrapping: 'pretty',
      }),
      body: role({
        family: 'body',
        minPx: 15,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.6,
        letterSpacing: '0',
        weight: 400,
        transform: 'none',
        maxCh: 36,
        align: 'start',
        wrapping: 'pretty',
      }),
      supporting: role({
        family: 'body',
        minPx: 13,
        maxPx: 14,
        vw: 0.8,
        lineHeight: 1.45,
        letterSpacing: '0.01em',
        weight: 400,
        transform: 'none',
        maxCh: 40,
        align: 'start',
        wrapping: 'pretty',
      }),
      kicker: quietKicker,
      navigation: role({
        family: 'body',
        minPx: 14,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.2,
        letterSpacing: '0.04em',
        weight: 500,
        transform: 'none',
        maxCh: 18,
        align: 'start',
        wrapping: 'normal',
      }),
      price: role({
        family: 'heading',
        minPx: 18,
        maxPx: 28,
        vw: 1.6,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 10,
        align: 'start',
        wrapping: 'normal',
      }),
      action: actionRole('start'),
    },
  },

  typographic_campaign: {
    grammarId: 'typographic_campaign',
    displayFont: 'Space Grotesk',
    headingFont: 'Space Grotesk',
    bodyFont: 'DM Sans',
    scaleRatio: 1.414,
    measureCh: 22,
    mobileScale: 0.78,
    roles: {
      display: role({
        family: 'display',
        minPx: 48,
        maxPx: 128,
        vw: 10.5,
        lineHeight: 0.82,
        letterSpacing: '-0.055em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 10,
        align: 'start',
        wrapping: 'balance',
      }),
      editorialHeading: role({
        family: 'display',
        minPx: 28,
        maxPx: 56,
        vw: 4.4,
        lineHeight: 0.9,
        letterSpacing: '-0.04em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 12,
        align: 'start',
        wrapping: 'balance',
      }),
      sectionHeading: role({
        family: 'heading',
        minPx: 18,
        maxPx: 28,
        vw: 2,
        lineHeight: 1.05,
        letterSpacing: '-0.03em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 16,
        align: 'start',
        wrapping: 'balance',
      }),
      body: role({
        family: 'body',
        minPx: 14,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.45,
        letterSpacing: '0',
        weight: 400,
        transform: 'none',
        maxCh: 28,
        align: 'start',
        wrapping: 'pretty',
      }),
      supporting: role({
        family: 'body',
        minPx: 12,
        maxPx: 13,
        vw: 0.75,
        lineHeight: 1.4,
        letterSpacing: '0.02em',
        weight: 400,
        transform: 'none',
        maxCh: 26,
        align: 'start',
        wrapping: 'pretty',
      }),
      kicker: role({
        family: 'body',
        minPx: 11,
        maxPx: 12,
        vw: 0.7,
        lineHeight: 1,
        letterSpacing: '0.22em',
        weight: 700,
        transform: 'uppercase',
        maxCh: 20,
        align: 'start',
        wrapping: 'normal',
      }),
      navigation: role({
        family: 'heading',
        minPx: 14,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.2,
        letterSpacing: '0.04em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 14,
        align: 'end',
        wrapping: 'normal',
      }),
      price: role({
        family: 'heading',
        minPx: 16,
        maxPx: 22,
        vw: 1.2,
        lineHeight: 1.15,
        letterSpacing: '-0.03em',
        weight: 600,
        transform: 'none',
        maxCh: 10,
        align: 'start',
        wrapping: 'normal',
      }),
      action: role({
        family: 'heading',
        minPx: 13,
        maxPx: 15,
        vw: 0.9,
        lineHeight: 1.15,
        letterSpacing: '0.04em',
        weight: 700,
        transform: 'uppercase',
        maxCh: 16,
        align: 'start',
        wrapping: 'normal',
      }),
    },
  },

  immersive_catalog: {
    grammarId: 'immersive_catalog',
    displayFont: 'DM Sans',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    scaleRatio: 1.2,
    measureCh: 40,
    mobileScale: 0.8,
    roles: {
      display: role({
        family: 'heading',
        minPx: 28,
        maxPx: 48,
        vw: 3.4,
        lineHeight: 1.05,
        letterSpacing: '-0.035em',
        weight: 500,
        transform: 'none',
        maxCh: 18,
        align: 'start',
        wrapping: 'balance',
      }),
      editorialHeading: role({
        family: 'heading',
        minPx: 20,
        maxPx: 28,
        vw: 1.8,
        lineHeight: 1.15,
        letterSpacing: '-0.025em',
        weight: 500,
        transform: 'none',
        maxCh: 22,
        align: 'start',
        wrapping: 'pretty',
      }),
      sectionHeading: role({
        family: 'heading',
        minPx: 16,
        maxPx: 20,
        vw: 1.2,
        lineHeight: 1.2,
        letterSpacing: '-0.02em',
        weight: 500,
        transform: 'none',
        maxCh: 28,
        align: 'start',
        wrapping: 'pretty',
      }),
      body: role({
        family: 'body',
        minPx: 14,
        maxPx: 15,
        vw: 0.9,
        lineHeight: 1.5,
        letterSpacing: '0',
        weight: 400,
        transform: 'none',
        maxCh: 40,
        align: 'start',
        wrapping: 'pretty',
      }),
      supporting: role({
        family: 'body',
        minPx: 12,
        maxPx: 13,
        vw: 0.75,
        lineHeight: 1.4,
        letterSpacing: '0.01em',
        weight: 400,
        transform: 'none',
        maxCh: 32,
        align: 'start',
        wrapping: 'pretty',
      }),
      kicker: role({
        family: 'body',
        minPx: 10,
        maxPx: 11,
        vw: 0.65,
        lineHeight: 1.2,
        letterSpacing: '0.16em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 24,
        align: 'start',
        wrapping: 'normal',
      }),
      navigation: role({
        family: 'body',
        minPx: 12,
        maxPx: 13,
        vw: 0.75,
        lineHeight: 1,
        letterSpacing: '0.04em',
        weight: 500,
        transform: 'none',
        maxCh: 16,
        align: 'start',
        wrapping: 'normal',
      }),
      price: role({
        family: 'body',
        minPx: 13,
        maxPx: 14,
        vw: 0.8,
        lineHeight: 1,
        letterSpacing: '0',
        weight: 500,
        transform: 'none',
        maxCh: 10,
        align: 'start',
        wrapping: 'normal',
      }),
      action: role({
        family: 'body',
        minPx: 12,
        maxPx: 13,
        vw: 0.75,
        lineHeight: 1,
        letterSpacing: '0.06em',
        weight: 600,
        transform: 'uppercase',
        maxCh: 16,
        align: 'start',
        wrapping: 'normal',
      }),
    },
  },

  warm_storytelling: {
    grammarId: 'warm_storytelling',
    displayFont: 'Fraunces',
    headingFont: 'Fraunces',
    bodyFont: 'Source Serif 4',
    scaleRatio: 1.25,
    measureCh: 48,
    mobileScale: 0.78,
    roles: {
      display: role({
        family: 'display',
        minPx: 34,
        maxPx: 68,
        vw: 4.8,
        lineHeight: 1.08,
        letterSpacing: '-0.02em',
        weight: 400,
        transform: 'none',
        maxCh: 16,
        align: 'start',
        wrapping: 'balance',
      }),
      editorialHeading: role({
        family: 'display',
        minPx: 24,
        maxPx: 38,
        vw: 2.6,
        lineHeight: 1.18,
        letterSpacing: '-0.015em',
        weight: 400,
        transform: 'none',
        maxCh: 20,
        align: 'start',
        wrapping: 'pretty',
      }),
      sectionHeading: role({
        family: 'heading',
        minPx: 18,
        maxPx: 26,
        vw: 1.6,
        lineHeight: 1.3,
        letterSpacing: '-0.01em',
        weight: 500,
        transform: 'none',
        maxCh: 24,
        align: 'start',
        wrapping: 'pretty',
      }),
      body: role({
        family: 'body',
        minPx: 17,
        maxPx: 19,
        vw: 1.1,
        lineHeight: 1.72,
        letterSpacing: '0.005em',
        weight: 400,
        transform: 'none',
        maxCh: 48,
        align: 'start',
        wrapping: 'pretty',
      }),
      supporting: role({
        family: 'body',
        minPx: 15,
        maxPx: 16,
        vw: 0.95,
        lineHeight: 1.6,
        letterSpacing: '0.01em',
        weight: 400,
        transform: 'none',
        maxCh: 40,
        align: 'start',
        wrapping: 'pretty',
      }),
      kicker: role({
        family: 'body',
        minPx: 12,
        maxPx: 13,
        vw: 0.75,
        lineHeight: 1.3,
        letterSpacing: '0.12em',
        weight: 500,
        transform: 'none',
        maxCh: 28,
        align: 'start',
        wrapping: 'normal',
      }),
      navigation: role({
        family: 'body',
        minPx: 13,
        maxPx: 14,
        vw: 0.8,
        lineHeight: 1.2,
        letterSpacing: '0.04em',
        weight: 400,
        transform: 'none',
        maxCh: 18,
        align: 'end',
        wrapping: 'normal',
      }),
      price: role({
        family: 'heading',
        minPx: 15,
        maxPx: 18,
        vw: 1,
        lineHeight: 1.2,
        letterSpacing: '0',
        weight: 500,
        transform: 'none',
        maxCh: 12,
        align: 'start',
        wrapping: 'normal',
      }),
      action: role({
        family: 'body',
        minPx: 13,
        maxPx: 14,
        vw: 0.8,
        lineHeight: 1.2,
        letterSpacing: '0.08em',
        weight: 500,
        transform: 'none',
        maxCh: 20,
        align: 'start',
        wrapping: 'normal',
      }),
    },
  },
};

export function typographyFor(grammarId: LayoutGrammarId): TypographySystem {
  return GRAMMAR_TYPOGRAPHY[grammarId];
}

export function roleCssVars(system: TypographySystem): Record<string, string> {
  const vars: Record<string, string> = {
    '--lg-display-font': `"${system.displayFont}", Georgia, serif`,
    '--lg-heading-font': `"${system.headingFont}", Georgia, serif`,
    '--lg-body-font': `"${system.bodyFont}", system-ui, sans-serif`,
    '--lg-scale-ratio': String(system.scaleRatio),
    '--lg-measure': `${system.measureCh}ch`,
    '--lg-mobile-scale': String(system.mobileScale),
  };
  (Object.keys(system.roles) as TypographyRoleId[]).forEach((id) => {
    const r = system.roles[id];
    const p = `--lg-${id}`;
    vars[`${p}-size`] = `clamp(${r.minPx}px, ${r.vw}vw, ${r.maxPx}px)`;
    vars[`${p}-lh`] = String(r.lineHeight);
    vars[`${p}-ls`] = r.letterSpacing;
    vars[`${p}-w`] = String(r.weight);
    vars[`${p}-tt`] = r.transform;
    vars[`${p}-ch`] = `${r.maxCh}ch`;
    vars[`${p}-align`] = r.align === 'start' ? 'left' : r.align === 'end' ? 'right' : 'center';
    vars[`${p}-wrap`] = r.wrapping;
  });
  return vars;
}

export const ALL_TYPOGRAPHY_ROLE_IDS: TypographyRoleId[] = [
  'display',
  'editorialHeading',
  'sectionHeading',
  'body',
  'supporting',
  'kicker',
  'navigation',
  'price',
  'action',
];
