/**
 * Expected SHA-256 of protected SpeedVendors commerce sources (runtime mirror).
 * Regenerated by: node tools/speedvendors-storefront-runtime/scripts/gen-protected-commerce-hashes.mjs
 *
 * On artifact ingest, if packageManifest.protectedCommerceSha256 is present and
 * differs from EXPECTED_HASHES → version fails (do not advance draft pointer).
 * Missing map (older packages) → skip (backward compatible).
 */

export const PROTECTED_COMMERCE_FILES = [
  'src/speedvendors/commerce.ts',
  'src/speedvendors/hooks.tsx',
  'src/speedvendors/index.ts',
  'src/speedvendors/mockCommerce.ts',
  'src/speedvendors/runtimeConfig.ts',
  'src/speedvendors/storeApiCommerce.ts',
  'src/speedvendors/types.ts',
  'src/speedvendors/ui/AddToCartButton.tsx',
  'src/speedvendors/ui/CartDrawer.tsx',
  'src/speedvendors/ui/CheckoutButton.tsx',
  'src/speedvendors/ui/CheckoutForm.tsx',
  'src/speedvendors/ui/CommerceLoading.tsx',
  'src/speedvendors/ui/FeaturedProducts.tsx',
  'src/speedvendors/ui/Footer.tsx',
  'src/speedvendors/ui/formatMoney.ts',
  'src/speedvendors/ui/Header.tsx',
  'src/speedvendors/ui/ProductCard.tsx',
  'src/speedvendors/ui/ProductDetail.tsx',
  'src/speedvendors/ui/ProductGrid.tsx',
  'src/speedvendors/ui/VariantSelector.tsx',
  'src/speedvendors/variantLabel.ts',
] as const;

/** Path → sha256 hex (of source file bytes at runtime tip). */
export const EXPECTED_PROTECTED_COMMERCE_SHA256: Record<string, string> = {
  'src/speedvendors/commerce.ts':
    '062fbc67dd12a6b82562818699260f652b58dc32dd3406a30d18036a4a868036',
  'src/speedvendors/hooks.tsx':
    'ec4c014b0eb3b2ec10ee1c1bd9cfa0ba035b114308faa7f3783ba24c5f9c774a',
  'src/speedvendors/index.ts':
    'd9e38ca212916b6584b2e48fe48255f247df199f1347a23f45d10268e515cbf5',
  'src/speedvendors/mockCommerce.ts':
    '7f7b23a40cfc35baac62266781fd57e431975e69711aedef188312d78b404593',
  'src/speedvendors/runtimeConfig.ts':
    '75002819811c3d06a827741ad0fdecd0d813f0111b23733493e39a6452c2a150',
  'src/speedvendors/storeApiCommerce.ts':
    '695360161a44640edbe1a5d601eb10c1fabb1568d3c9f954aefebc040aaf1402',
  'src/speedvendors/types.ts':
    'ca96c049e7b957ab94e87c3664ce112b502529cfe73f41b6f2896930d0aad07c',
  'src/speedvendors/ui/AddToCartButton.tsx':
    '0b9cd8166e1ba5143e8550815b4c2a21d5e8032610f16c24041fbb1bd26a13ad',
  'src/speedvendors/ui/CartDrawer.tsx':
    '6ea5fc1823129a90e3233b7eef7c41ab22fc8536ffd31587690547c7f173a21c',
  'src/speedvendors/ui/CheckoutButton.tsx':
    'abf012fdc704aa33622ed181d45e4b743e2f26e5d916b27588737514ee315d10',
  'src/speedvendors/ui/CheckoutForm.tsx':
    '201d3b37d3f62cc8f5c3e90e26628bce920f7abfcb9932d6bac72c3f3555deae',
  'src/speedvendors/ui/CommerceLoading.tsx':
    '7b0f2d84dae36c44431f24dc2174caa4e60f4608b80d7b18f268c6abe520360c',
  'src/speedvendors/ui/FeaturedProducts.tsx':
    '9c4e0d99443b9ad791a523d82713c1ba2d2df1ac779e5867dbb0481f0bab14fb',
  'src/speedvendors/ui/Footer.tsx':
    '6089d9fbec29c3734dae1d7dc7027e0b68c604b386645b3a00a4dcb2eb752f03',
  'src/speedvendors/ui/formatMoney.ts':
    '675711147c24067b260ce27e194b19865281d25b5de8f08a11453a243aaf35d7',
  'src/speedvendors/ui/Header.tsx':
    'e1eb83e6cb699503aeb479bd1e95c5602fd304949df0fdf96dd6d8c64ffbdc41',
  'src/speedvendors/ui/ProductCard.tsx':
    'dcd809a1d8b339748e9034cf3656985a94cfb2015db70820977d4b4c9c8ed98d',
  'src/speedvendors/ui/ProductDetail.tsx':
    'da6e16208ab1a93fc3389ed266521ebc6e3e19c21fc1edfe4640e0ef682689ca',
  'src/speedvendors/ui/ProductGrid.tsx':
    '3dd550b66caa45e3f76c5744baf8fab74a3b514f22283bf6868d090659a7db1b',
  'src/speedvendors/ui/VariantSelector.tsx':
    '3983457e67630112fca201ea1b2c7db6369cb4ef47a9aa552868388955f31fbc',
  'src/speedvendors/variantLabel.ts':
    'caf92774726e62d721817658a206e70d4bb7929a260e9630572253dba9dfbaca',
};

export type ProtectedCommerceAssertResult =
  | { ok: true; skipped: true; reason: 'missing_map' }
  | { ok: true; skipped: false }
  | { ok: false; error: string; mismatches: string[] };

/**
 * When manifest.protectedCommerceSha256 is present, every expected path must match.
 * Unknown extra keys in the package map are ignored; missing expected keys → fail.
 */
export function assertProtectedCommerceHashes(
  packageManifest: Record<string, unknown> | null | undefined,
  expected: Record<string, string> = EXPECTED_PROTECTED_COMMERCE_SHA256,
): ProtectedCommerceAssertResult {
  if (!packageManifest || typeof packageManifest !== 'object') {
    return { ok: true, skipped: true, reason: 'missing_map' };
  }
  const raw = packageManifest.protectedCommerceSha256;
  if (raw == null || typeof raw !== 'object' || Array.isArray(raw)) {
    return { ok: true, skipped: true, reason: 'missing_map' };
  }
  const got = raw as Record<string, unknown>;
  const mismatches: string[] = [];
  for (const [rel, want] of Object.entries(expected)) {
    const actual = got[rel];
    if (typeof actual !== 'string' || actual.toLowerCase() !== want.toLowerCase()) {
      mismatches.push(
        `${rel}: expected ${want.slice(0, 12)}… got ${
          typeof actual === 'string' ? actual.slice(0, 12) + '…' : String(actual)
        }`,
      );
    }
  }
  if (mismatches.length > 0) {
    return {
      ok: false,
      error: 'protected_commerce_hash_mismatch',
      mismatches,
    };
  }
  return { ok: true, skipped: false };
}
