/**
 * Expected SHA-256 of protected SpeedVendors commerce sources (runtime mirror).
 * Regenerated by: node tools/speedvendors-storefront-runtime/scripts/gen-protected-commerce-hashes.mjs
 *
 * On artifact ingest, if packageManifest.protectedCommerceSha256 is present and
 * differs from EXPECTED_HASHES → version fails (do not advance draft pointer).
 * Missing map (older packages) → skip (backward compatible).
 */

export const PROTECTED_COMMERCE_FILES = [
  'src/speedvendors/commerce.ts',
  'src/speedvendors/storeApiCommerce.ts',
  'src/speedvendors/runtimeConfig.ts',
  'src/speedvendors/types.ts',
  'src/speedvendors/hooks.tsx',
] as const;

/** Path → sha256 hex (of source file bytes at runtime tip aaf6ed1…). */
export const EXPECTED_PROTECTED_COMMERCE_SHA256: Record<string, string> = {
  'src/speedvendors/commerce.ts':
    '804b7aada1a6ae11ac10e68237b1c339dab10c564908213b18fdb6de5d9c374f',
  'src/speedvendors/storeApiCommerce.ts':
    '53c5359e2259c87393b581141db816fcdfe48230b9210dae9809f6fd366369dc',
  'src/speedvendors/runtimeConfig.ts':
    'a00ed38f3c8313abc1d2d9b90206d4a0a51eb8511b5534a89fb5c46adbddafa6',
  'src/speedvendors/types.ts':
    '509fb05fa225f637f71467c58a0325692e8f62681a69e73575cbcf3e2b89d84c',
  'src/speedvendors/hooks.tsx':
    'f6922f60a09528b3476910022661be4f25e790e087e2825bac7eda2a43c3ebe6',
};

export type ProtectedCommerceAssertResult =
  | { ok: true; skipped: true; reason: 'missing_map' }
  | { ok: true; skipped: false }
  | { ok: false; error: string; mismatches: string[] };

/**
 * When manifest.protectedCommerceSha256 is present, every expected path must match.
 * Unknown extra keys in the package map are ignored; missing expected keys → fail.
 */
export function assertProtectedCommerceHashes(
  packageManifest: Record<string, unknown> | null | undefined,
  expected: Record<string, string> = EXPECTED_PROTECTED_COMMERCE_SHA256,
): ProtectedCommerceAssertResult {
  if (!packageManifest || typeof packageManifest !== 'object') {
    return { ok: true, skipped: true, reason: 'missing_map' };
  }
  const raw = packageManifest.protectedCommerceSha256;
  if (raw == null || typeof raw !== 'object' || Array.isArray(raw)) {
    return { ok: true, skipped: true, reason: 'missing_map' };
  }
  const got = raw as Record<string, unknown>;
  const mismatches: string[] = [];
  for (const [rel, want] of Object.entries(expected)) {
    const actual = got[rel];
    if (typeof actual !== 'string' || actual.toLowerCase() !== want.toLowerCase()) {
      mismatches.push(
        `${rel}: expected ${want.slice(0, 12)}… got ${
          typeof actual === 'string' ? actual.slice(0, 12) + '…' : String(actual)
        }`,
      );
    }
  }
  if (mismatches.length > 0) {
    return {
      ok: false,
      error: 'protected_commerce_hash_mismatch',
      mismatches,
    };
  }
  return { ok: true, skipped: false };
}
