/**
 * Safe catalogue metadata for the Novatee theme (no secrets / no commerce).
 */
export const novateeManifest = {
  id: 'novatee' as const,
  name: 'Novatee',
  shortDescription:
    'Dark streetwear storefront with neon accents, graphic-tee hero art, and hosted checkout.',
  categoryTags: ['streetwear', 'dark', 'neon', 'fashion', 'graphic-tees'],
  previewImage: '/themes/novatee/preview.svg',
  availableContentSlots: [
    'logo',
    'announcement',
    'hero.mediaMode',
    'hero.image',
    'hero.featuredProductId',
    'hero.backgroundImage',
    'hero.eyebrow',
    'hero.headline',
    'hero.headlineAccent',
    'hero.supportingCopy',
    'hero.primaryCtaLabel',
    'hero.secondaryCtaLabel',
    'marqueeItems',
    'shopEyebrow',
    'shopTitle',
    'featuredEyebrow',
    'featuredFallbackTitle',
    'featuredFallbackBody',
    'whyEyebrow',
    'whyTitle',
    'whyCards',
    'footerTagline',
    'footerPaymentsCopy',
    'navLabels',
    'heroStats',
    'footerExploreTitle',
    'footerPaymentsTitle',
    'socialLinks',
    'merchantTaglineFallback',
    'sections',
  ],
  supportedHeroMediaModes: ['template-art', 'image', 'featured-product'] as const,
};
