/**
 * Novatee editable-field schema — drives the generic curated-theme form.
 * Keep keys aligned with ContentSlots / NOVATEE_CONTENT_DEFAULTS / runtime defaults.
 */
import type { CuratedThemeEditorSchema } from './editorSchema';

export const NOVATEE_EDITOR_SCHEMA: CuratedThemeEditorSchema = {
  themeId: 'novatee',
  fields: [
    {
      key: 'logo',
      label: 'Logo',
      group: 'Brand',
      type: 'image',
      helpText: 'Shown in the header. Uses the SpeedVendors media library.',
    },
    {
      key: 'announcement',
      label: 'Announcement bar',
      group: 'Brand',
      type: 'text',
      maxLength: 120,
      placeholder: 'Secure payments · Fast delivery',
    },
    {
      key: 'sections',
      label: 'Marketing sections',
      group: 'Sections',
      type: 'section-controls',
      helpText:
        'Show, hide, and reorder optional marketing blocks. Shop, hero, cart and checkout cannot be removed.',
    },
    {
      key: 'hero.mediaMode',
      label: 'Hero media',
      group: 'Hero',
      type: 'choice',
      options: [
        { value: 'template-art', label: 'Keep Novatee artwork' },
        { value: 'image', label: 'Upload / select an image' },
        { value: 'featured-product', label: 'Use a featured product' },
      ],
    },
    {
      key: 'hero.image',
      label: 'Hero image',
      group: 'Hero',
      type: 'image',
      visibleWhen: { key: 'hero.mediaMode', equals: 'image' },
    },
    {
      key: 'hero.featuredProductId',
      label: 'Featured product',
      group: 'Hero',
      type: 'product',
      helpText: 'Live catalog — prices come from commerce.',
      visibleWhen: { key: 'hero.mediaMode', equals: 'featured-product' },
    },
    {
      key: 'hero.backgroundImage',
      label: 'Promotional background (optional)',
      group: 'Hero',
      type: 'image',
    },
    {
      key: 'hero.eyebrow',
      label: 'Eyebrow',
      group: 'Hero',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'hero.headline',
      label: 'Headline',
      group: 'Hero',
      type: 'text',
      maxLength: 120,
    },
    {
      key: 'hero.headlineAccent',
      label: 'Headline accent',
      group: 'Hero',
      type: 'text',
      maxLength: 80,
      helpText: 'Shown on the gradient line under the headline.',
    },
    {
      key: 'hero.supportingCopy',
      label: 'Supporting description',
      group: 'Hero',
      type: 'textarea',
      maxLength: 400,
      helpText: 'Leave empty to use your live store name + tagline.',
    },
    {
      key: 'merchantTaglineFallback',
      label: 'Fallback tagline',
      group: 'Hero',
      type: 'textarea',
      maxLength: 400,
      helpText: 'Used when supporting copy is empty and your store has no tagline.',
    },
    {
      key: 'hero.primaryCtaLabel',
      label: 'Primary CTA',
      group: 'Hero',
      type: 'text',
      maxLength: 60,
    },
    {
      key: 'hero.secondaryCtaLabel',
      label: 'Secondary CTA',
      group: 'Hero',
      type: 'text',
      maxLength: 60,
    },
    {
      key: 'heroStats',
      label: 'Hero feature stats',
      group: 'Hero',
      type: 'hero-stats',
      maxCount: 6,
      helpText: 'Short highlights under the hero CTAs (max 6).',
    },
    {
      key: 'marqueeItems',
      label: 'Marquee items',
      group: 'Sections',
      type: 'string-list',
      maxCount: 24,
      maxLength: 80,
      helpText: 'One item per line.',
    },
    {
      key: 'shopEyebrow',
      label: 'Shop eyebrow',
      group: 'Shop',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'shopTitle',
      label: 'Shop title',
      group: 'Shop',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'featuredEyebrow',
      label: 'Featured eyebrow',
      group: 'Featured',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'featuredFallbackTitle',
      label: 'Featured fallback title',
      group: 'Featured',
      type: 'text',
      maxLength: 120,
      helpText: 'Used when the live featured product has no title.',
    },
    {
      key: 'featuredFallbackBody',
      label: 'Featured fallback body',
      group: 'Featured',
      type: 'textarea',
      maxLength: 400,
    },
    {
      key: 'whyEyebrow',
      label: 'Why eyebrow',
      group: 'Why us',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'whyTitle',
      label: 'Why title',
      group: 'Why us',
      type: 'text',
      maxLength: 120,
    },
    {
      key: 'whyCards',
      label: 'Why cards',
      group: 'Why us',
      type: 'why-cards',
      maxCount: 8,
    },
    {
      key: 'navLabels',
      label: 'Navigation labels',
      group: 'Navigation',
      type: 'nav-labels',
      maxLength: 40,
    },
    {
      key: 'footerTagline',
      label: 'Footer tagline',
      group: 'Footer',
      type: 'textarea',
      maxLength: 240,
    },
    {
      key: 'footerExploreTitle',
      label: 'Footer explore heading',
      group: 'Footer',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'footerPaymentsTitle',
      label: 'Footer payments heading',
      group: 'Footer',
      type: 'text',
      maxLength: 80,
    },
    {
      key: 'footerPaymentsCopy',
      label: 'Footer payments copy',
      group: 'Footer',
      type: 'textarea',
      maxLength: 320,
    },
    {
      key: 'socialLinks',
      label: 'Social links',
      group: 'Social',
      type: 'social-links',
      maxCount: 8,
      helpText: 'http(s) URLs only.',
    },
  ],
};
